version: '2'

services:

  zookeeper:
    image: jplock/zookeeper:3.4.9
    restart: always
    expose:
      - "2181"
      - "2888"
      - "3888"

  kafka:
    image: p1ck/kafka
    links:
        - zookeeper:zookeeper
    ports:
        - "9092:9092"
    restart: always
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_BROKER_ID=1
      - ZOOKEEPER_CONNECTION_STRING=zookeeper:2181
